name: Unzip and Commit

on:
  workflow_dispatch:

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      
      - name: Install unzip
        run: sudo apt-get install unzip
      
      - name: Unzip file
        run: unzip yourfile.zip -d unzipped_folder
      
      - name: Commit unzipped files
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          cp -r unzipped_folder/* .
          rm -rf yourfile.zip
          git add .
          git commit -m "Unzipped files"
          git push
